### ISSUE TITLE
Add Logging and Error Handling

### ISSUE THREAD

**Issue by nickna** [nickna/Neighborly#22]
#### **Description:**
Enhance the logging and error handling mechanisms in Neighborly to provide more informative and actionable logs and error messages.

#### **Tasks:**
- Implement a consistent logging strategy across the codebase, using a logging framework like Serilog or NLog.
- Improve error messages to be more descriptive and helpful.
- Ensure that all critical operations have appropriate error handling and logging.

#### **Resources:**
- [Serilog Documentation](https://serilog.net/)
- [NLog Documentation](https://nlog-project.org/)

#### **Impact:**
Enhanced logging and error handling will make it easier to diagnose and fix issues, improving the stability and maintainability of Neighborly.

#### **How to Contribute:**
1. Fork the repository and create a new branch for your changes.
2. Implement the logging and error handling improvements.
3. Ensure all new and existing tests pass.
4. Submit a pull request with a detailed description of the changes.

**Comment by nickna** [comment]
Added logging support in this commit: 0644adace84783c06e773bb9d3a55353b5fe502b

**Comment by hangy** [comment]
> Added logging support in this commit: [0644ada](https://github.com/nickna/Neighborly/commit/0644adace84783c06e773bb9d3a55353b5fe502b)

To be honest, I'd move the concrete logger from the library to the API. At least if the idea is to enable [using the package as an in-memory vector db in a program](https://github.com/nickna/Neighborly/blob/b28eefc59812f7ec8f7cc5c75b9cddd826e34b1b/README.md#client-library-nuget-package), then it would be better to just log to `Microsoft.Extensions.Logging.Abstractions`, and allow consumers of the NuGet package to define their own log targets.
