### ISSUE TITLE
Potential race condition with MemoryMappedList ctor

### ISSUE THREAD

**Issue by nickna** [nickna/Neighborly#62]
I'm investigating an issue where unit tests intermittently fail to access the physical files they've created.
The tests pass when run individually. They fail or lock when run as a batch. 
This may be a Windows-related issue with file creation being inadvertently async. 

![image](https://github.com/nickna/Neighborly/assets/4017153/28636e92-07dc-4de6-a4fd-d7f2cf4bb9ea)

CC: @hangy

**Comment by nickna** [comment]
_ stream = _ file. CreateViewStream() `is causing the exception: MemoryMappedFile System.IO.IOException: The paging file is too small for this operation to complete.

This is likely because the previous file(s) were not released before a new one was created. 
On Windows, MemoryMappedFile is limited based on virtual memory size, so it will not allocate more virtual memory than it has. 

More to come...

**Comment by hangy** [comment]
One issue seems to be that `VectorDatabase` doesn't implement `IDisposable`. It should do so, so that `VectorList` gets disposed cleanly

**Comment by hangy** [comment]
It seems to me that with the current amount of memory allocated by the virtual files (albeit being sparse files) on Windows, they seem to break some limit if more than 2 instances of `VectorDatabase` are present at the same time. I was able to work around some of those issues with #63.

When running all tests, the system memory seems to be exhausted (I think it was running the Defrag tests at this point):
![image](https://github.com/nickna/Neighborly/assets/87124/de5efe55-fb28-4222-95a9-ac6c0998a76b)

**Comment by nickna** [comment]
That was quick. Your PR fixed the issue. Thank you!
