### ISSUE TITLE
Add support for Search by Text

### ISSUE THREAD

**Issue by nickna** [nickna/Neighborly#86]
**Description:**

VectorDatabase exposes a search function that takes a Vector as an input.
A embeddings function is needed to convert strings to dense vectors, but we do not currently bundle one with our project.
This adds complexity to greenfield projects and may require developers to have a third-party dependency that incurs cost.

**Functionality:**

Expose a search-by-text function in `VectorDatabase`.
Add a utility class to convert text to `Vector.Values` (float array).

**Decisions & Caveats:**

Make reasonable default choices for the model used for embeddings.
- The model should be open-source under a permissible license.
- The model should be hosted on GitHub or Hugging Face.

A tokenizer should be chosen once for the entire database.
- Consider adding an event to VectorDatabase that triggers when a new embeddings model is chosen.
If the user elects to switch embeddings models, retrigger vectorization for all existing data.

Ensure the utility class can handle various languages and edge cases in text processing.
Provide options for developers to plug in their own tokenizer models if they prefer. (It's okay to force a format such as pth or onnx)

**Tasks:**

Implement integration with PyTorch to use its models for vector embeddings.
Create examples and documentation demonstrating how to use these integrations.
Resources:

[PyTorch.NET](https://github.com/SciSharp/Torch.NET)

**Impact:**
This new class library will eliminate the need for a third-party embeddings function. It will incur a tradeoff in terms of space and compute complexity, as we may want to bundle a pretrained ONNX or PyTorch model with this new library.

**How to Contribute:**

- Fork the repository and create a new branch for your changes.
- Create a unit test class for your work
- Submit a pull request with a description of the changes.

**Comment by hangy** [comment]
I don't really use Python so I don't know that PyTorch library. Providing an integration with such a 3rd party system via a plugin system could be useful, but having Python as a necessary runtime(?) dependency to install in a .NET environment sounds weird to me.

[Microsoft.ML.Tokenizers](https://github.com/dotnet/machinelearning/blob/9ffb3a31753df5690257f5b59b1ba334fae6501e/src/Microsoft.ML.Tokenizers/PACKAGE.md), for example, comes with a few open source tokenizers and doesn't seem to require external dependencies

**Comment by nickna** [comment]
I made a mistake in this task description: I meant to call this an embeddings function, not a tokenizer, which is a preprocessing step for transformers. 

Your suggestion for using Microsoft.ML instead of Pytorch.NET or another dependency is still valid. I wanted to use various large models for embeddings but realized this was a huge performance hurdle and not needed.
